### ISSUE TITLE
Rename to lower-case

### ISSUE THREAD

**Issue by mossblaser** [SpiNNakerManchester/DataSpecification#1]
Since our packages are all Python modules and Python modules have the strong convention of being all lower-case I suggest renaming repositories to match. In this case `data_allocation` would be better.

**Comment by alan-stokes** [comment]
So im just trying to clean up our issue tracker to see whats essential and move them to spynnaker (this being where we want to move all issues to for central management). 

On this topic, I think that it would require a rewrite of all the code for its imports, and python ides are not  very good for this. Its also that all the pypi stuff would need be to changed to adjust for the new naming convention. 

Given this amount of workload, id dare say its not worth our time on a naming convention. Thus ill close this issue here. If you feel it is more inportant, please feel free to move this to spynnaker (its not just DataSpecification, all the modules go thorugh the Java naming convention) and copy the comments over. 

alan
